### ISSUE TITLE
[Q] OpenMPI application with custom PMIx keys 

### ISSUE THREAD

**Issue by angainor** [openpmix/openpmix#1427] opened 2019-09-03 13:09 UTC
(tested with PMIx 2.1.4) 

I have a problem using both MPI and PMIx calls in the same application, related to the [async modex](https://github.com/pmix/pmix/issues/1424) we discussed earlier. I use OpenMPI, so the PMIx support is there, and the OpenMPI runtime already initializes it and uses it internally. I initialize my client after `MPI_Init`. After that my application tries to use PMIx to spread some custom, user-specified per-rank information. Essentially:

```
MPI_Init_thread(...);                                                                                                                                           
PMIx_init(&myproc, NULL, 0);

// set custom key
PMIx_Put(...)
PMIx_Commit(...)

// fence or no fence (!)
PMIx_Fence_nb(..., &lock)
// wait for completion
LOCK_WAIT(&lock);

// get peers custom value
PMIx_Get(...)
```
Now, the `PMIx_Get(...)` only works if I run the fence and do an explicit exchange. If I don't, then I get an error -46. I guess after OpenMPI initializez PMIx (and maybe runs a fence) then PMIx thinks it has all the data. So when I add a new key, it simply figures out that such key doesn't exist and errors out. I tested that by initializing the PMIx client and setting the custom key before I run MPI_Init, and then I don't need a fence for my key to be available. I also tried to add `-mca pmix_base_async_modex 1` to `mpirun`, but that didn't help.

Is that the desired behavior?

Thanks!

**Comment by rhc54** [comment] 2019-09-03 13:31
Just a quick sanity check: your custom key does not begin with "pmix", does it? That would not be allowed.

Otherwise, your method should work. However, PMIx 2.1.4 might have a bug that causes the problem. You might try with v2.2.3: https://github.com/pmix/pmix/releases/tag/v2.2.3

**Comment by angainor** [comment] 2019-09-03 13:34
> Just a quick sanity check: your custom key does not begin with "pmix", does it? That would not be allowed.

Nope, starts with `ghex`.

Thanks! I'll try with a newer version and let you know.

**Comment by angainor** [comment] 2019-09-03 15:46
@rhc54 Unfortunately I see the same behavior with 2.2.3. The old version is installed system-wide, so I hope I linked everything correctly:
```
$ ldd /cluster/projects/nn9999k/marcink/software/openmpi/4.0.1/lib/openmpi/mca_pmix_ext2x.so
	libpmix.so.2 => /cluster/projects/nn9999k/marcink/software/pmix/2.2.3/lib/libpmix.so.2 (0x00002b31eceb2000)
[...]
$ ldd ./test
	libpmix.so.2 => /cluster/projects/nn9999k/marcink/software/pmix/2.2.3/lib/libpmix.so.2 (0x00002b30056b1000)
```

**Comment by rhc54** [comment] 2019-09-03 15:59
Okay, I'll try to reproduce it here

**Comment by rhc54** [comment] 2019-09-03 21:36
I just tried it with PMIx master running against PRRTE master and it worked fine. I am going to update OMPI master with PMIx master - could you then try your test there? If it doesn't work, then we know the problem is in OMPI and not PMIx.

Just trying to narrow it down.

**Comment by angainor** [comment] 2019-09-04 06:20
Sure, I can do that. Let me know when.

**Comment by rhc54** [comment] 2019-09-04 06:23
It's ready now, so whenever you have a chance 😄

**Comment by angainor** [comment] 2019-09-04 06:57
Just a sanity check: did you run the ranks on different compute nodes? If you run them on the same node, then it works as expected.

**Comment by angainor** [comment] 2019-09-10 13:21
@rhc54 Hi, Ralph! Just wondering if you managed to reproduce this with my code, or is there something I'm doing wrong?

**Comment by rhc54** [comment] 2019-09-10 13:33
My apologies - nothing wrong with your code. I'm working on another (possibly related) problem and will report back when this is addressed.

**Comment by angainor** [comment] 2019-09-10 13:47
thanks! np, I'll wait :)

**Comment by rhc54** [comment] 2019-09-11 02:45
I believe this is now fixed - at least, it is working for me. Please give it a try and let me know.

**Comment by angainor** [comment] 2019-09-12 07:22
Heh. I've accidentally found that it seems to be the UCX pml that breaks things. The below runs the defaults (with UCX) and doesn't work:
```
$ mpirun -mca coll_hcoll_enable 0 -H c3-3,c3-4 -map-by node ./pmixtest
PMIx_Put on ghex-rank-address
PMIx initialized
PMIx_Commit on ghex-rank-address
PMIx_Put on ghex-rank-address
PMIx_Commit on ghex-rank-address
Thu Sep 12 09:18:12 2019 ERROR: pmixtest.c:55  Client ns 1120993281 rank 1: PMIx_Get ghex-rank-address: -46

Thu Sep 12 09:18:12 2019 ERROR: pmixtest.c:55  Client ns 1120993281 rank 0: PMIx_Get ghex-rank-address: -46
```
While all seems to be fine when I disable the UCX pml:
```
 mpirun -mca coll_hcoll_enable 0 -mca pml ^ucx -H c3-3,c3-4 -map-by node ./pmixtest
PMIx initialized
PMIx_Put on ghex-rank-address
PMIx_Put on ghex-rank-address
PMIx_Commit on ghex-rank-address
PMIx_Commit on ghex-rank-address
PMIx_get ghex-rank-address returned 256 bytes
PMIx_get ghex-rank-address returned 256 bytes
PMIx finalized
```

Moreover, the behavior is the same in both scenarios for both the `ompi-master`, and for my original test setup (4.0.1 with pmix 2.1.4). So it seems to be indeed something specific to ompi. Hope that gives some hints..

**Comment by angainor** [comment] 2019-09-13 07:40
I see the exact same behavior with PRTE and OMPI master. In order to have my key distributed correctly I have to `PMIx_set` it before I call `MPI_Init`. I guess this is a fine work-around, but it's strange nonetheless. 

I looked at the source, and there is nothing special in the UCX pml: a few calls to `OPAL_MODEX_SEND / RECV` is all.

**Comment by rhc54** [comment] 2019-09-13 07:44
I would suggest opening an issue on OMPI and citing this one. There may be something going on with respect to UCX that we don't know about. Offhand, I agree that the connection seems odd, but the fact that it is completely reproducible would seem to indicate that there is something there, and it doesn't appear to be a problem in PMIx itself. Cite @artpol84 on the issue to get his attention.

**Comment by angainor** [comment] 2019-09-13 07:52
It might not be the UCX pml itself, but rather the fact that I use any pml at all, for example. I guess on my system this is the only option I have.

**Comment by rhc54** [comment] 2019-09-13 12:22
There is always an active PML - if not the UCX one, then ob1 or cm will be used. This is something specific to the ucx pml. The fact that it works when you don't specify the pml indicates that things work fine with ob1, which is the default pml, so this is something specific to the ucx pml for some reason.

**Comment by rhc54** [comment] 2020-01-10 00:19
@angainor Please take a look at https://github.com/openpmix/prrte/pull/297 and see if this alternative approach might meet your needs. I have also linked you in to the general community discussion on this topic.

**Comment by rhc54** [comment] 2020-03-30 21:39
Believe this has been resolved.

**Closed by rhc54** 2020-03-30 21:39 UTC
