### ISSUE TITLE
Refactoring of the PTL components

### ISSUE THREAD

**Issue by artpol84** [openpmix/openpmix#1241] opened 2019-05-10 02:14 UTC
The PTL code refactoring

While working on #1240 I faced that the PTL code is quite not maintainable:
* connect handler functions for both TCP and USOCK are huge:
  * TCP: [736 lines](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp_component.c#L982:L1730)
  * USOCK: [423 lines](https://github.com/pmix/pmix/blob/master/src/mca/ptl/usock/ptl_usock_component.c#L342:L765)
* In both mentioned functions above error handling code is duplicated many times
  * This contributes to poor readability
  * As well as to error-prone maintenance as it is required to go over all of theses error cases and update them if needed
  * I already see several places where error paths have erroneously deviated.
* The code for connection_handler, ack_send, ack_recv in TCP and USOCK are similar. We need to push this code to the "base"
* As the result USOCK is out of date at least with respect to recv ack:
  * USOCK doesn't have the codepath for tools [link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/usock/ptl_usock.c#L384)
  * TCP has it: [link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1253:L1334)
* Some of the exchanges are hidden inside macro which also obscures the code, e.g.:
  * PMIX_PSEC_VALIDATE_CONNECTION implicitly sends the message [link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp_component.c#L1653)
     * I believe this caused #1240 to appear
     * I think that protocol exchanges have to be highlighted and straightforward.

Those are just observations from the quick review.

**Comment by rhc54** [comment] 2019-05-10 03:35
I think you overestimate the problem, though I agree that the code needs some cleanup. The usock component is not allowed to support tools by design - that was written into the standard (only tcp can support tool connections). The TCP and USOCK codes are similar but different - the reason for keeping them separate is that the usock code is strictly to support the legacy v1.2.x series. It is not intended for continued use and is therefore in a "frozen" state.

So some of what you observe is by intent. Some is spread that occurred over time and needs to be consolidated. I can play with it a bit over time.

**Comment by artpol84** [comment] 2019-05-10 05:35
> usock component is not allowed to support tools by design - that was written into the standard (only tcp can support tool connections). 

This has to be obvious from the code itself and not require consulting with original developer.

**Comment by artpol84** [comment] 2019-05-10 05:38
> he TCP and USOCK codes are similar but different - the reason for keeping them separate is that the usock code is strictly to support the legacy v1.2.x series.

This is the worst scenario when 2 code paths look similar but have minor deviations not obvious from the code review. 700 lines is really hard to keep in mind and compare.

The right way would be to have base functionality that is common and only retain the differences in the components.

**Comment by artpol84** [comment] 2019-05-10 05:41
The issue I found today was deeply masked and was sitting there for 2 years.
And there is no way one can find them from reviewing the code.
Partially because of the exchange hidden in that psec macro. Partially because of the huge functions.

**Comment by rhc54** [comment] 2020-11-18 20:14
@artpol84 Take a gander at #1931 - I believe it is at least a first step towards resolving your concerns.

**Comment by rhc54** [comment] 2021-01-09 09:17
This can be reopened or a new ticket filed if someone wants to take a further look at it, but I believe the issues raised here have at least partially been resolved with the refactoring released in v4.0.

**Closed by rhc54** 2021-01-09 09:17 UTC
Labels: enhancement
