### ISSUE TITLE
4.1.2 src/util/keyval fails on missing keyval_lex.c

### ISSUE THREAD

**Issue by dvzrv** [openpmix/openpmix#2599] opened 2022-05-20 12:58 UTC
### What version of the PMIx Reference Library are you using?
4.1.2

### Describe how PMIx was installed 
I'm trying to build from the auto-generated source tarball, as it is directly derived from the sources in this repository and not modified.

### Please describe the system on which you are running

* Operating system/version: Arch Linux
* Computer hardware: x86_64
* Network type: n/a

-----------------------------

## Details of the problem

Running the following

```shell
./autogen.pl
./configure --prefix=/usr
make V=1
```

leads to 

```
Making all in util/keyval
make[2]: Entering directory '/build/openpmix/src/openpmix-4.1.2/src/util/keyval'
/bin/sh ../../.././config/ylwrap keyval_lex.l lex.pmix_util_keyval_yy.c keyval_lex.c -- : -Ppmix_util_keyval_yy
depbase=`echo keyval_lex.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../src/include -I../../../include   -iquote/build/openpmix/src/openpmix-4.1.2 -iquote/build/openpmix/src/openpmix-4.1.2/src -I/build/openpmix/src/openpmix-4.1.2/include   -MT keyval_lex.lo -MD -MP -MF $depbase.Tpo -c -o keyval_lex.lo keyval_lex.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src/include -I../../../include -iquote/build/openpmix/src/openpmix-4.1.2 -iquote/build/openpmix/src/openpmix-4.1.2/src -I/build/openpmix/src/openpmix-4.1.2/include -MT keyval_lex.lo -MD -MP -MF .deps/keyval_lex.Tpo -c keyval_lex.c  -fPIC -DPIC -o .libs/keyval_lex.o
cc1: fatal error: keyval_lex.c: No such file or directory
compilation terminated.
make[2]: *** [Makefile:747: keyval_lex.lo] Error 1
make[2]: Leaving directory '/build/openpmix/src/openpmix-4.1.2/src/util/keyval'
make[1]: *** [Makefile:1607: all-recursive] Error 1
make[1]: Leaving directory '/build/openpmix/src/openpmix-4.1.2/src'
make: *** [Makefile:947: all-recursive] Error 1
```

Full build log in packaging environment: 
[openpmix-4.1.2-build.log](https://github.com/openpmix/openpmix/files/8740178/openpmix-4.1.2-build.log)

The generated file `src/util/keyval/keyval_lex.c` is not present after running `./autogen.pl` and `./configure`, which makes me wonder how it is created, as this does not seem to differ much from how [make_tarball()](https://github.com/openpmix/openpmix/blob/e11fe2aecf05761080b7aa011976e71034473b87/contrib/make_dist_tarball#L261-L307) does things.
Am I missing something?

**Comment by rhc54** [comment] 2022-05-20 13:31
Do you have `flex` on your machine? The file `keyval_lex.c` is generated by `flex` when we build the official release tarballs. However, we only do that when we see we are in a Git repository - I'm pretty sure GitHub wouldn't include all the Git subdirectories that indicate "this is a repository clone". So I suspect the `flex`-generated files (there are a couple of them, IIRC) are all missing.

**Comment by rhc54** [comment] 2022-05-20 13:32
We do have a warning on the page somewhere about not using those tarballs. Sadly, GitHub doesn't have an option to "not build" them.

**Comment by dvzrv** [comment] 2022-05-20 14:10
Thanks for the quick response! :)

> Do you have `flex` on your machine? The file `keyval_lex.c` is generated by `flex` when we build the official release tarballs.

Yes, the build environment has flex 2.6.4.

> However, we only do that when we see we are in a Git repository

Hm, that's odd. Why is that? Without this limitation wouldn't it allow everyone to just use the auto-generated tarball and build using the below?

```
./autogen.pl
./configure --prefix=/usr
make V=1
```

> I'm pretty sure GitHub wouldn't include all the Git subdirectories that indicate "this is a repository clone". So I suspect the `flex`-generated files (there are a couple of them, IIRC) are all missing.

I am not sure I follow. What does the inclusion of the generated files have to do with github or git?
A release tarball based on e.g. a tag of this repository could be created in a temporary directory by either using a tarball derived from [git-archive](https://man.archlinux.org/man/git-archive.1) (which is effectively what VCS forges to AFAIK) or a fresh clone of this repository.
Why can files only be generated if creating the release tarball from a cloned repository?

> We do have a warning on the page somewhere about not using those tarballs. Sadly, GitHub doesn't have an option to "not build" them.

I understand that you would like to provide "pre-autotooled" release tarballs, but I do not understand why building from an autogenerated tarball should not be supported. Is there a specific reason for it?

**Comment by rhc54** [comment] 2022-05-20 14:34
This spans some 18 years of history. The problem is that most systems don't include `flex`, or (less likely) don't include a version we can use. Requiring that `configure` always run `flex` is therefore a problem. We maintain a few machines that have the required capability, and we generate the official release tarballs on those. This removes a significant obstacle to installation, at least for most people.

We _could_ add logic to configure to allow running of `flex` if requested, or if the generated files aren't present. My only answer is that we simply haven't done so, and it isn't much of a priority to do it. This was never an issue until GitHub started posting its own tarballs, so we kinda lay the blame on them for creating the problem.

If someone wants to write the necessary "glue" to run `flex` when available and necessary (i.e., generated files are not present), I'm happy to accept that contribution. Otherwise, this is unlikely to be done anytime soon.

**Comment by rhc54** [comment] 2022-05-25 02:10
See if #2606 helps resolve the problem - it targets the master branch, but might/should apply with minimal issue to the v4.1.2 branch.

**Comment by rhc54** [comment] 2022-06-01 23:50
Fixed by https://github.com/openpmix/openpmix/pull/2616

**Closed by rhc54** 2022-06-01 23:50 UTC
