### ISSUE TITLE
Performance degradation 2.1 against 2.0

### ISSUE THREAD

**Issue by karasevb** [openpmix/openpmix#434] opened 2017-07-21 13:45 UTC
There are results of PMIx perf tools, measured for versions 2.1 (master) and 2.0 for messages and dstore. The results show an increase memory consumption and an increase timings for PMIx v2.1 as for `message` and for `dstore`.  All tests were got on 4x16 ppn.

![image](https://user-images.githubusercontent.com/17932065/28464540-eb073f0e-6e4f-11e7-8de2-0cd7e82e80e2.png)

**Comment by rhc54** [comment] 2017-07-21 13:49
Interesting. The memory footprint is, of course, the bigger concern because of the enormous jump. There is some overhead of using components instead of direct code, but nowhere near enough to account for that difference.

Any thoughts?

**Comment by karasevb** [comment] 2017-07-21 14:17
The `dstore` looks like it does not work correctly, because memory has grown strongly. I have no supposition now, this requires investigation.

**Comment by artpol84** [comment] 2017-07-21 16:54
Our plan was:
1. Make it work
2. Do the perf optimization.
We shifted to the phase 2 now.

**Comment by karasevb** [comment] 2017-08-14 09:46
There are updated results:
![image](https://user-images.githubusercontent.com/17932065/29266021-5be6bbb2-810d-11e7-9fcc-6899f7b97660.png)
As seen, the footprint problem of v2.1 was addressed. Oldest measure of `375498.75` Kb was reduced to `44682.85` Kb, that looks like as for v2.0.
The latest measurements was did with included of PRs: #439, #461

**Comment by karasevb** [comment] 2017-08-14 09:51
@artpol84 @rhc54 
Can we close an issue?

**Comment by artpol84** [comment] 2017-08-14 14:00
Thanks @karasevb .
However all performance characteristics are worse compared to v2.0. We need to keep this issue until we resolve all of them.

**Comment by artpol84** [comment] 2017-08-14 14:08
Please, provide comparison to v1.2.1 as well.

**Comment by karasevb** [comment] 2017-08-15 09:03
There is results for v1.2:
![image](https://user-images.githubusercontent.com/17932065/29305527-5da4e152-81c3-11e7-908a-0a3aca401622.png)

**Comment by rhc54** [comment] 2017-08-26 03:20
I found the source of at least some of this performance issue. In v2.1, we cannot cache the job-level info in a packed buffer because we do not know in advance the GDS component that the client will be using. So we use a GDS function to cache the job-level info in the server's hash component.

When the first client from that job connects to the server, we determine which GDS component shall be used for clients of that job. We then fetch the cached job-level info from the server's hash component, and use the GDS store_job_info function to deliver it. The expectation is that the dstore component will populate the dstore on the first call, and ignore all subsequent calls for that job.

What is happening right now is that the dstore component is taking the job-level info and packing it into a buffer that it caches in its own pmix_value_array. It then unpacks the buffer and populates the shmem region. It appears that it does this in case it needs the data again at some future point. However, there is no need for the component to cache anything as the info is always cached in the hash component.

As a result, we now have two caches of the job-level info, plus an unnecessary pack/unpack of that info. Should be relatively easy to fix, I should think, assuming this analysis is correct.

**Comment by karasevb** [comment] 2017-09-14 11:23
There are new results regarding PR #509. The scope of test is 31x20ppn.
![image](https://user-images.githubusercontent.com/17932065/30426285-ab32e2e2-9975-11e7-85fa-897b005c40c8.png)

These two tables show the memory consumption on the server side of the test per node in Kb. The total reduced for `dstor` is 148 467Kb, and for `msg` 69 987 Kb.
![image](https://user-images.githubusercontent.com/17932065/30426717-452501ae-9977-11e7-88ab-f5f531cd71ba.png)

![image](https://user-images.githubusercontent.com/17932065/30426753-669a5c30-9977-11e7-9c87-658b09f71690.png)

**Comment by rhc54** [comment] 2017-12-08 15:50
Do we know any more about this? Is it still an issue, or do we have it under control and can close this?

**Comment by artpol84** [comment] 2017-12-08 22:40
@karasevb please re-evaluate.

**Comment by rhc54** [comment] 2018-12-19 21:50
I believe this has been resolved, yes? If so, can you please close it?

**Comment by artpol84** [comment] 2018-12-20 10:51
@rhc54, I'd like to keep this until after NY holidays (mid Jan) due to vacations in our group.

**Comment by artpol84** [comment] 2018-12-20 10:51
I mean we are going to re-evaluate and close once 100% sure.

**Comment by jjhursey** [comment] 2019-12-06 15:14
I'm going to close this ticket given the age of this ticket, and that most work has moved to the master and v3.1 branches. Feel free to file a new ticket (or reopen this one) if performance regressions still need to be investigated.

**Closed by jjhursey** 2019-12-06 15:14 UTC
Labels: bug

**Comment by artpol84** [comment] 2019-12-11 18:04
Thanks, @jjhursey
