### ISSUE TITLE
PMIx_Get of namespace that exists locally seems to auto-fail

### ISSUE THREAD

**Issue by dsolt** [openpmix/openpmix#1158] opened 2019-03-21 22:15 UTC
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

3.1

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version:  linux 
* Computer hardware:  IBM Power
* Network type: TCP

-----------------------------

## Details of the problem

I hit the following issue:   If a client asks for data (in my example a simple pmix app is asking for the job data PMIX_LOCAL_SIZE) of another namespace that HAS been registered on the node, the CL appears to recognize the namespace and does not call server_dmodex_req (the RM), but returns -17.  If the client does the exact same request but asks for its own namespace, the call succeeds, so I'm pretty sure that PMIX_LOCAL_SIZE is being correctly provided by the PMIx_server_register_nspace call on the server.

```
#include <stdlib.h>
#include <stdio.h>
#include <pmix.h>

int main(int argc, char *argv[]) {
pmix_proc_t proc, myproc, mywildnspace;
pmix_value_t *val;
int rc;
rc = PMIx_Init(&myproc, NULL, 0);

strcpy(proc.nspace, argv[1]);
proc.rank = PMIX_RANK_WILDCARD; 
strcpy(mywildnspace.nspace, myproc.nspace);
mywildnspace.rank = PMIX_RANK_WILDCARD;
// if argv[1] is non-existing namespace, then sever_dmodex_req comes up to RM
// if argv[1] does exist under the local CL instance, then it returns failure
rc = PMIx_Get(&proc, PMIX_LOCAL_SIZE, NULL, 0, &val); // this call fails 
fprintf(stderr, "rc of not my proc: %d\n", rc);
if (!rc) fprintf(stderr, "Value is %d\n", val->data.integer);
rc = PMIx_Get(&mywildnspace, PMIX_LOCAL_SIZE, NULL, 0, &val);  // this call works
fprintf(stderr, "rc of my nspace LOCAL: %d\n", rc);
if (!rc) fprintf(stderr, "Value is %d\n", val->data.integer);

// PMIx_Finalize();
}
```

**Comment by artpol84** [comment] 2019-03-21 22:42
@dsolt would be nice to rule out dstore (which seems to be an issue from the first sight)
* Can you try to disable ds21
* Can you disable both ds21 and ds12
And see that happens.

**Comment by dsolt** [comment] 2019-03-22 14:32
Yes, when I set export PMIX_MCA_gds=hash the problem goes away and it works as expected.

**Comment by dsolt** [comment] 2019-03-22 14:38
PMIX_MCA_gds=ds12,hash  fails

**Comment by artpol84** [comment] 2019-03-23 00:55
I assume ds21 also fails?

**Comment by artpol84** [comment] 2019-03-23 00:57
@karasevb I think we can reproduce this with our CI multi-server feature.
Please take it next week.

**Comment by rhc54** [comment] 2019-07-24 18:36
@artpol84 @karasevb Was this ever resolved?

**Comment by artpol84** [comment] 2019-07-25 02:31
No, thanks for pinging

**Comment by rhc54** [comment] 2019-08-20 16:33
I believe this has been fixed by other commits - the dstore "fastpath" checks will fail as the value won't be in the dstore, but the next thing we do is check the hash table which should find the info.

@dsolt Can you please confirm?

**Comment by jjhursey** [comment] 2019-12-12 21:50
@dsolt is this good to close or is there more work to do?

**Comment by rhc54** [comment] 2020-03-31 16:27
@dsolt Please reopen if this remains an issue, but I believe this has been fixed.

**Closed by rhc54** 2020-03-31 16:27 UTC
Labels: bug
