### ISSUE TITLE
pmdl/ompi: OMPI_MCA_* environment variables take precedence over 

### ISSUE THREAD

**Issue by ggouaillardet** [openpmix/openpmix#2548] opened 2022-03-25 01:17 UTC
per open-mpi/ompi#10159, command line MCA parameters do not take precedence over `OMPI_MCA_*` environment variable.

I took a crack at it, and after a failed attempt, I came up with the fix below:
now, `PMIX_ADD_ENVAR` is used for `OMPI_MCA_*` environment variables instead of `PMIX_SET_ENVAR`.

@rhc54 could you please review this?

```patch
diff --git a/src/mca/pmdl/ompi/pmdl_ompi.c b/src/mca/pmdl/ompi/pmdl_ompi.c
index dc961b9b..30fd2ab7 100644
--- a/src/mca/pmdl/ompi/pmdl_ompi.c
+++ b/src/mca/pmdl/ompi/pmdl_ompi.c
@@ -310,6 +310,18 @@ harvest:
                             : mca_pmdl_ompi_component.excparms);
         rc = pmix_util_harvest_envars(mca_pmdl_ompi_component.include,
                                       mca_pmdl_ompi_component.exclude, ilist);
+       /* OMPI_MCA_* harvested variables inherited from the environment should not overwrite
+        * those set by the command line and/or config files */
+        PMIX_LIST_FOREACH (kv, ilist, pmix_kval_t) {
+            if (PMIX_ENVAR != kv->value->type) {
+                continue;
+            }
+            if (0 == strncmp(kv->value->data.envar.envar, "OMPI_MCA_", 9)) {
+               free(kv->key);
+               kv->key = strdup(PMIX_ADD_ENVAR);
+           }
+       }
+
         if (PMIX_SUCCESS != rc) {
             return rc;
         }
```

**Comment by rhc54** [comment] 2022-03-25 02:28
The precedence chain is:

config file is overwritten by environment, which is overwritten by cmd line.

What we have defined is a method for ensuring we adhere to it. I assume something has broken it as otherwise you wouldn't be citing some problem. Key is that PMIx will harvest the config files, not PRRTE - this ensures the config files are read even when using a direct launch (eg., srun).

PMIx then checks the environment and overwrites the config values as required, passing the results up to PRRTE. PRRTE then is supposed to overwrite those with anything from the cmd line, passing the result as part of the app's environment.

My guess is that this has all been confused by the activity in PRRTE, probably not fully coordinated with what is happening in PMIx. I know the cmd line parser is only just solidifying and that the schizo personalities continue to be in flux.

For example, a quick glance shows that we are parsing the cmd line into the environment, which is what ORTE used to do but won't work for PRRTE. Some of it is my fault - wound up focusing a lot on PRRTE and trying to "transition" the old OPAL cmd line parser, and you tend to lose the thread of what is going on elsewhere. Some of the problem also stems from the complexity introduced by all this "tuned" file crap, with multiple files all overwriting each other, combined with setting and forwarding envars in files and on the cmd line, layered on top of layer after layer. Sigh.

We need to spend a little time working thru the logic progression to clean things up. I'll do it for PRRTE in the next few weeks - you folks can use that as an example for resolving the OMPI problems. Will take a little while as there are other things needing attention - and frankly, this isn't a high priority. 😄 

If you want to work on it in the meantime, I'd suggest going into the schizo/ompi component of PRRTE. Assume you have an environment passed up to you from PMIx that contains whatever resulted from scanning the config files merged with what is in the environment. Now work thru the "logic" (I quote it because it is highly illogical) tree for handling the tuned files and cmd line options, merging the results into the environment you were passed. You want to end up with the environment properly set for that application - PRRTE will take responsibility for forwarding it as required.

**Comment by ggouaillardet** [comment] 2022-03-25 12:57
Thanks Ralph for the length explanation.
I could not spend as much time as I would like to on Open MPI / PRRTE / PMIx, and indeed, quite a lot of things have changed.

If I grok it correctly, in `schizo/ompi`, `app->env` is set from the command line (e.g. the `--mca` parameters), but is then overwritten, notably by the environment of the command line.

The patch below (for PRRTE) ultimately overwrite the `app->env` with what was set from the command line.
I am not convinced this is the most elegant approach, but since this is a blocker for Open MPI 5, that might be good enough for the time being.

```patch
diff --git a/src/mca/schizo/ompi/schizo_ompi.c b/src/mca/schizo/ompi/schizo_ompi.c
index d0c99c9d56..5249d0c600 100644
--- a/src/mca/schizo/ompi/schizo_ompi.c
+++ b/src/mca/schizo/ompi/schizo_ompi.c
@@ -1541,6 +1541,7 @@ static int setup_fork(prte_job_t *jdata, prte_app_context_t *app)
     bool exists;
     char *param, *p2, *saveptr;
     int i;
+    char **app_env = prte_argv_copy(app->env);
 
     /* flag that we started this job */
     prte_setenv("PRTE_LAUNCHED", "1", true, &app->env);
@@ -1676,6 +1677,18 @@ static int setup_fork(prte_job_t *jdata, prte_app_context_t *app)
         }
     }
 
+    /* make sure the app env that was set by mpirun has not been overwritten */
+    for (char **p = app_env; *p; p++) {
+       p2 = strchr(*p, '=');
+       /* can this even happen ? */
+       if (NULL == p2) {
+            continue;
+       }
+       *p2++ = '\0';
+       prte_setenv(*p, p2, true, &app->env);
+    }
+    prte_argv_free(app_env);
+
     return PRTE_SUCCESS;
 }
```

**Comment by rhc54** [comment] 2022-03-25 13:44
I'm afraid this patch is operating in the wrong place. The function it touches is called on the backend nodes just prior to fork/exec of the application's proc. The envars it is setting are the ones already determined by `mpirun` to be set for the app, so you really don't want to mess with them. Your patch would effectively just do a "no-op" by resetting anything `mpirun` said to do, which wouldn't be a good idea.

The problem needs to be resolved at the frontend of the launch procedure by ensuring that the environment is constructed according to the precedence tree. The rules for PRRTE and OMPI personalities are somewhat different (e.g., PRRTE doesn't have all that tuned file complexity), so it will take a little effort on the part of the OMPI team to get it correctly resolved.

I can provide advice/guidance if desired. I just have other things to do before tackling the PRRTE side of this problem.

**Comment by ggouaillardet** [comment] 2022-03-25 14:29
Thanks Ralph, I will definitely welcome your guidance!

The issue I am seeing (and I tried to work around) is

 - PMIx harvest the environment (e.g. `OMPI_MCA_coll=invalid`)

 -  PRRTE adds `OMPI_MCA_coll=libnbc,basic` to `app->env` from the `-mca` command line

 - PRRTE overwrite `app->env` with the environment PMIx previously harvested (so we end up with `OMPI_MCA_coll=invalid`


The first patch I proposed was to use `PMIX_ADD_ENVAR` when a `OMPI_MCA_*` environment variable is harvested by PMIx (so it will not overwrite any value that could be set by PRRTE)

The second attempt make sure we use the environment that is implicitly set by the command line

An other approach could be to have PRRTE update the environment **before** it is harvested by PMIx.
Could this be the recommended approach?

**Comment by rhc54** [comment] 2022-03-25 18:25
This is going to take a multi-step approach, so bear with me a bit 😄  Here is how this is supposed to work:

* PRRTE detects the "OMPI" personality is being used. Among other things, it needs to call `PMIx_Setup_application` requesting that envars be harvested and passing down the "ompi" personality. This tells the pmdl/ompi component that it should look for its associated values
* The environment returned from "setup_app" is provided as the base environment to the PRRTE schizo "parse_env" function. This gives you the opportunity to override the config file/envars with the cmd line.

The actions occurring in "setup_fork" are happening due to directives that were included in the call to `PMIx_Spawn`. These will override anything else that was given since it comes directly from the application. In the case of `mpirun`, there should be no directives and "setup_fork" basically is a "no-op".

From what I can see, the code flow appears to be doing the right thing. I would look to see where PRRTE is doing this overwrite. One possibility I can see: it appears that PRRTE calls "setup_app" in "odls_base_default_fns.c" when it does the "get_add_procs_data" function. The odls needs to do this so we can allocate network resources, which requires that we have mapped the job.

If you look around line 373, you'll see this:
```c
    /* if they haven't harvested envars, do so now */
    if (!prte_get_attribute(&jdata->attributes, PRTE_JOB_ENVARS_HARVESTED, NULL, PMIX_BOOL)) {
        PMIX_INFO_LIST_ADD(ret, ilist, PMIX_SETUP_APP_ENVARS, NULL, PMIX_BOOL);
    }
```
If that flag isn't set, then we will ask PMIx to once again harvest the envars in addition to doing the network allocations - and that would indeed overwrite anything PRRTE did. I suspect this is the source of the problem.

What you might do, then, is verify that the `PRTE_JOB_ENVARS_HARVESTED` attribute is correctly being added to the job. I'm trying to think of why we wouldn't have already harvested them - this might be a holdover from earlier times. IIRC, this originally was added to ensure that the DVM didn't harvest envars if `prun` was being used - ensured we took the envars local to the user and not wherever the DVM controller happened to be running. We could probably resolve that better now by just having `prte` never harvest envars, and allow `prterun` and `prun` to do so - thereby removing the need for that attribute.

Anyway, I hope that points you in the right direction. Like I said, I suspect this attribute is not being set and therefore the odls is causing PMIx to overwrite the envars.

**Comment by ggouaillardet** [comment] 2022-03-26 08:36
Thanks again!

indeed, `PRTE_JOB_ENVARS_HARVESTED` is not set.

That being said, I noted `PMIx_server_setup_application()` is first invoked by `mpirun` on namespace `xyz@0`.
Later, `odls` check the `PRTE_JOB_ENVARS_HARVESTED` attribute but on namespace `xyz@1` (which is not set).
Moreover, the last PMIx harvesting is done with the base pmdl (read not the `ompi` one)
For testing purpose I did as if `PRTE_JOB_ENVARS_HARVESTED` was set in `odls` but it did not make any difference.

> The environment returned from "setup_app" is provided as the base environment to the PRRTE schizo "parse_env" function. This gives you the opportunity to override the config file/envars with the cmd line.

the `schizo/ompi` `parse_env()` callback is invoked on `prte_launch_environ`. It is the full environment of `mpirun --mca coll foo` minus the `PMIX_*` and `PRTE_*` environment variables.
The result is  `app->env = { "OMPI_MCA_coll=foo", NULL }` environment.
Does that look good so far? or should we have basically `prte_launch_environ` plus `OMPI_MCA_coll=foo`?


finally in `setup_fork`, `OMPI_MCA_coll` takes the value that was harvested (before the command line is parsed) because PMIx used `PMIX_SET_ENVAR`.
(which means that in this case, the environment takes precedence over the command line)
So if we
`OMPI_MCA_coll=invalid mpirun --mca coll foo ...`
the MPI app has `OMPI_MCA_coll=invalid` in its environment.


A new option could be PRRTE tells PMIx so `PMIX_SET_ENVAR` a variable that is passed by the command line, but that sounds very convoluted (and I am not sure there is a mechanism to achieve that yet).
I am afraid I cannot see any good option to fix that so I'll just be patient :-)

**Comment by rhc54** [comment] 2022-03-26 14:52
Patience is a virtue 🤷‍♂️ 

I'm afraid that the OMPI team's decision to re-use `prte` for `mpirun` created this kind of conflict. PRRTE by design does not transfer anything from the cmd line to applications it launches - there is no such thing as a "PRRTE app". It also caused this kind of weird looping to occur as we now have apps being specified on the cmd line.

It'll take a while to figure out how to cleanly separate the two use-cases.

**Comment by awlauria** [comment] 2022-03-28 18:12
As a temporary patch, would it not make sense to throw all mca's into the environment during cli parse time?

```
[awlauria@f10n17 openpmix]$ git diff src/util/pmix_cmd_line.c
diff --git a/src/util/pmix_cmd_line.c b/src/util/pmix_cmd_line.c
index 9e9cbd68..8f5c1faa 100644
--- a/src/util/pmix_cmd_line.c
+++ b/src/util/pmix_cmd_line.c
@@ -137,6 +137,10 @@ int pmix_cmd_line_parse(char **pargv, char *shorts,
                      * will have been incremented since the MCA param options
                      * require an argument */
                     pmix_asprintf(&str, "%s=%s", argv[optind-1], argv[optind]);
+                    char *tmp_mca_env;
+                    pmix_asprintf(&tmp_mca_env, "OMPI_MCA_%s", argv[optind-1]);
+                    setenv(tmp_mca_env, argv[optind], 1);
+                    free(tmp_mca_env);
                     mystore(myoptions[option_index].name, str, results);
                     free(str);
                     ++optind;
```
This seems to fix the problem in my setup. This happens before `parse_env`, so it'll overwrite what is in the users environment, and it'll work its way through to be propagated to compute nodes.

Is there any drawbacks to this approach?

**Comment by rhc54** [comment] 2022-03-28 18:29
It will only work for the `mpirun` use-case, so I'd rather not do it. Better to wait and fix it right.

**Comment by awlauria** [comment] 2022-03-28 18:43
I can only seem to reproduce with mpirun with ompi `mca` parameters (or with prterun + --personality ompi)

```
$ export PMIX_MCA_foo=A
$. ./exports/bin/prterun --pmixmca foo B --np 2 --host "hostA:1,hostB:1" env | grep -i PMIX_MCA_foo
PMIX_MCA_foo=B
PMIX_MCA_foo=B
$. ./exports/bin/prterun --np 2 --host "hostA:1,hostB:1" env | grep -i PMIX_MCA_foo
PMIX_MCA_foo=A
PMIX_MCA_foo=A
```

**Comment by rhc54** [comment] 2022-03-28 18:47
I think @ggouaillardet has adequately documented that we need to review the code path here. Let's not do anything until we can clean up those paths to something sane and then see if anything further is required.

The case you are missing is the PRRTE DVM and the user executing apps via `prun`. Again, patience is a virtue - there are no reports of anyone dying or mass suicides as a result of this problem, so let's take the time to fix it cleanly.

**Comment by awlauria** [comment] 2022-03-28 18:58
Hmm, I cannot reproduce with prte + prun:

```
$. ./exports/bin/prte --hostfile ./hostfile &
[1] 2305050
$. DVM ready

$. ./exports/bin/prun --np 2 --host "hostA:1,hostB:1" env | grep -i PMIX_MCA_foo
PMIX_MCA_foo=test
PMIX_MCA_foo=test
$. ./exports/bin/prun --pmixmca foo B --np 2 --host "hostA:1,hostB:1" env | grep -i PMIX_MCA_foo
PMIX_MCA_foo=B
PMIX_MCA_foo=B
```

**Comment by awlauria** [comment] 2022-03-28 22:05
Based on my findings that this seems to be ompi specific, I was able to find that the parse_cli() function in schizo/ompi was not exposing the ompi mca parameters like it was doing for prte/pmix mca parameters.

PR here: https://github.com/openpmix/openpmix/issues/2548

**Comment by rhc54** [comment] 2022-07-26 01:21
We can consider this closed by the PRRTE change that was accepted - follow-on cleanup will be under the PRRTE issue.

**Closed by rhc54** 2022-07-26 01:21 UTC
