### ISSUE TITLE
Latest mainline failing with latest hwloc

### ISSUE THREAD

**Issue by qkoziol** [openpmix/openpmix#3099] opened 2023-06-22 20:59 UTC
## Background information

Mainline build of openpmix failing against mainline build of hwloc.

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

Occurs on both my Intel-based Mac and on a Linux server.

-----------------------------

## Details of the problem

I'm building OpenPMIx from github mainline, against the latest mainline hwloc, and the build is failing with:

```
  CC       common/pmix_attributes.lo
  CC       common/pmix_data.lo
  CC       common/pmix_iof.lo
hwloc/pmix_hwloc.c:507:46: error: use of undeclared identifier 'HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1'; did you mean 'HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V2'?
                                             HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1)) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V2
/Users/qkoziol/HPC/OpenMPI/ompi_issue_11532/install/include/hwloc/export.h:40:2: note: 'HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V2' declared here
 HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V2 = (1UL<<1)
 ^
hwloc/pmix_hwloc.c:778:13: error: use of undeclared identifier 'HWLOC_OBJ_NODE'; did you mean 'HWLOC_OBJ_CORE'?
        if (HWLOC_OBJ_NODE != type && HWLOC_OBJ_PACKAGE != type &&
            ^~~~~~~~~~~~~~
            HWLOC_OBJ_CORE
/Users/qkoziol/HPC/OpenMPI/ompi_issue_11532/install/include/hwloc.h:218:3: note: 'HWLOC_OBJ_CORE' declared here
  HWLOC_OBJ_CORE,       /**< \brief Core.
  ^
hwloc/pmix_hwloc.c:797:22: error: use of undeclared identifier 'HWLOC_OBJ_NODE'; did you mean 'HWLOC_OBJ_CORE'?
                case HWLOC_OBJ_NODE:
                     ^~~~~~~~~~~~~~
                     HWLOC_OBJ_CORE
/Users/qkoziol/HPC/OpenMPI/ompi_issue_11532/install/include/hwloc.h:218:3: note: 'HWLOC_OBJ_CORE' declared here
  HWLOC_OBJ_CORE,       /**< \brief Core.
  ^
hwloc/pmix_hwloc.c:861:22: error: duplicate case value 'HWLOC_OBJ_CORE'
                case HWLOC_OBJ_CORE:
                     ^
hwloc/pmix_hwloc.c:797:22: note: previous case defined here
                case HWLOC_OBJ_NODE:
                     ^
4 errors generated.
make[2]: *** [hwloc/pmix_hwloc.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by rhc54** [comment] 2023-06-22 21:42
Neither I nor PMIx "mainline" drugs - nor, I suspect, do @bgoglin and HWLOC. So I presume you mean something else?

**Comment by bgoglin** [comment] 2023-06-22 21:50
Don't use hwloc git master, it's currently preparing to 3.0. It comes with some small API changes that aren't finalized yet, and the removal of old v1 backward compatibility stuff. Use branch "v2.x" if you really want the latest unstable code without API changes (it'll become v2.10 in the future).

That said, PMIx should switch from HWLOC_OBJ_NODE to HWLOC_OBJ_NUMANODE since this dates from hwloc 1.11 (hwloc<3 redefines HWLOC_OBJ_NODE on top of it, 3.0 doesn't).

HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1 will disappear in 3.0. It will only be compatible with 2.x.

**Comment by rhc54** [comment] 2023-06-22 21:56
Ouch - that's awfully hard for me to do, @bgoglin. There are a number of releases already out there that use those terms, and they will suddenly fail with the newest HWLOC releases. No way to recall them.

Can you just retain them as "deprecated", like PMIx does to avoid breaking existing codes?

**Comment by bosilca** [comment] 2023-06-22 22:17
These were deprecated for the entire lifetime of the 2.x. At some point existing code need to be updated ;)

**Comment by bgoglin** [comment] 2023-06-22 22:18
NODE is deprecated since november 2014 (but it's a #define hence no warning).
XML 1.x compatibility is going away because the code is a pain to maintain and 2.0 is 5 years old already (and there's no way to keep it and mark it deprecated).

The 3.0 transition will take years, it won't be widely installed a year, it won't be in Linux distributions before more than that. People will have plenty of time to update pmix to a newer version before anybody forces them to upgrade hwloc. And hwloc 2.x will be maintained for years as usual.

**Comment by rhc54** [comment] 2023-06-22 22:22
And OMPI is the first to complain loudly at me when I update code and break backward compatibility. What I would have to do is put configure logic in that blacklists HWLOC versions with incompatible definitions - and then OMPI will scream about that too.

Truly, I get it - keeping backward compatibility is a pain. However, container folks need it, we are constantly criticized when we break it, etc.

I have no issue blacklisting HWLOC versions if that's what's required. Can't do that for prior releases, but can start simply adding to every PMIx and PRRTE release configure code that errors out for HWLOC releases other than those verified to work with it.

Guess that's probably the best path forward 🤷‍♂️

**Comment by bgoglin** [comment] 2023-06-23 05:25
You don't have to blacklist anything. If you're going to update old release series to say "I don't compile with hwloc 3.0" (which is already said by the compile failure messages), you should rather update those release series to compile with hwloc 3.0, it will be much easier than the 1.x->2.0 transition.

**Comment by rhc54** [comment] 2023-06-23 12:23
My concern is going forward, not backward. If you are going to continue the policy of breaking backward compatibility, which is entirely your right, then I need to future-protect the PMIx and PRRTE releases. One can argue that compile-time breakage is an adequate "canary", but the problem is that users don't understand that marker and instead come back here to report it as a "bug".

However, you've also indicated that you are going to start re-using symbols that were previously deprecated, assigning new behavior and/or meaning to them. This won't result in a compile-time break, but will result in unintended behavior that would be very hard to track down.

Accordingly, I see no option but to add configure tests that correlate to the hwloc levels we know work. I don't like that solution because it blocks backward compatible future releases, but we know we have a problem with hwloc >= 3, so that is an obvious place to start.

What I propose to do is add configure checks/blocks to generate errors for hwloc > 2 in PMIx v3-5 and PRRTE v3-4. I can also try to do it at runtime (using your API version) to handle the case where we are compiled against one version and then run against a different one.

I don't know if there will ever be a PMIx 6 or PRRTE 5 (I am skeptical of the PRRTE case, frankly), so this may prove a long-term situation. Not sure how one goes about dealing with that - software using PMIx in particular can have long lives. I suspect it will just be another entry in the packager's compatibility matrix, so maybe that isn't such a big deal.

**Comment by rhc54** [comment] 2023-06-23 12:29
> > However, you've also indicated that you are going to start re-using symbols that were previously deprecated, assigning new behavior and/or meaning to them. This won't result in a compile-time break, but will result in unintended behavior that would be very hard to track down.
> 
> Where did I say that?

(hwloc<3 redefines HWLOC_OBJ_NODE on top of it, 3.0 doesn't).

Implies that HWLOC_OBJ_NODE will now be defined as something different, yes? Or did you mean to imply that it simply no longer exists at all?

**Comment by rhc54** [comment] 2023-06-23 12:44
Okay, so if I add a configure check for hwloc < 3, then I should be fine for compile and reduce the user complaint volume.

IIRC, the soname should be sufficient to protect against someone building us against hwloc < 3 and then runtime loading a hwloc >= 3 with us. So I don't think I have to add any protection there.

Make sense?

**Comment by bgoglin** [comment] 2023-06-23 12:46
Yes.

**Comment by rhc54** [comment] 2023-06-23 12:48
Kewl - thanks!

**Comment by rhc54** [comment] 2023-06-23 19:33
Fixed with configure changes

**Closed by rhc54** 2023-06-23 19:33 UTC
