### ISSUE TITLE
PMIx_Get that forces a server_dmodex call will cause the next PMIx_Fence to hang

### ISSUE THREAD

**Issue by dsolt** [openpmix/openpmix#1404] opened 2019-08-19 19:44 UTC
Thank you for taking the time to submit an issue!

## Background information
git master @ 4ce90e2da06243cd5cf64cbf0c3d3df8ba503276

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### Please describe the system on which you are running

* Operating system/version:  linux
* Computer hardware:  power 9
* Network type:  NA

-----------------------------

## Details of the problem

I am currently working with 2 namespaces.  They happen to be a child and parent, but not sure that is important:

PMIx_Fence (across both namespaces);
PMIx_Put()
PMIx_Commit()
PMIx_Get()
PMIx_Fence (across both namespaces);

If there is only a single namespace, everything works fine, but when there are two namespaces, the 2nd fence hangs.  If I get rid of the PMIx_Get calls, then the 2nd fence does not hang.   If I get rid of the PMIx_Fence call from just the parent, then only the server where the child is running will fail to call server_fence_nb in the server library.  If I get rid of the PMIx_Fence call from the child, then only the server where the parent is running will fail to call server_fence_nb in the server library.

**Comment by rhc54** [comment] 2019-08-21 17:02
@dsolt You do a put, commit - and then a get? Given that the fence hasn't happened yet, the values won't have been circulated. So what value are you "get"ing?

**Comment by rhc54** [comment] 2019-08-21 17:05
FWIW: I reproduced your program, with the "get" being of the hostname of a process in the other nspace, and it worked just fine with PRRTE and current PMIx master.

**Comment by jjhursey** [comment] 2019-12-12 22:10
@dsolt is this specific to dstore (per issue #1414)? We may need a reproducer reference program.

**Comment by rhc54** [comment] 2020-03-31 16:26
@dsolt Any update on this problem? Are you still seeing it?

**Comment by dsolt** [comment] 2020-04-03 21:24
it's been a while... let me try to see where this is at.

**Comment by rhc54** [comment] 2021-03-24 13:01
Closing this since I haven't been able to replicate in quite some time. Please reopen if you see it again.

**Closed by rhc54** 2021-03-24 13:01 UTC
